# Generated by Django 6.0.4 on 2026-04-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('tracto', 'Tracto'), ('caja', 'Caja')], max_length=10, verbose_name='Tipo de Activo')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número Económico')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('transmission', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transmisión')),
                ('operator', models.CharField(blank=True, max_length=150, null=True, verbose_name='Operador')),
                ('operator_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Operador')),
                ('engine', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motor')),
                ('plates', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placas')),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensiones')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condición')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['-created_at'],
            },
        ),
    ]
