# Generated by Django 6.0.4 on 2026-04-23 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título del Servicio')),
                ('description', models.TextField(verbose_name='Descripción del Problema/Servicio')),
                ('service_type', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='correctivo', max_length=20)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('esperando_insumos', 'Esperando Cotización/Insumos'), ('terminado', 'Terminado')], default='pendiente', max_length=30)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.asset', verbose_name='Activo')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'home_maintenance_service',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Insumo')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('needs_purchase', models.BooleanField(default=False, verbose_name='¿Requiere Compra?')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario (Admin)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='home.maintenanceservice')),
            ],
            options={
                'db_table': 'home_service_supply',
            },
        ),
    ]
